services:
  timezone-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run dev
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M